"""update SalesModel - add status

Revision ID: 0a784e67ecf7
Revises: 351b0097bc7b
Create Date: 2021-06-18 23:31:16.203761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a784e67ecf7'
down_revision = '351b0097bc7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'status')
    # ### end Alembic commands ###
