"""update SalesModel - add field client v1.5

Revision ID: 351b0097bc7b
Revises: 0ea311529aaf
Create Date: 2021-06-18 19:17:16.738486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351b0097bc7b'
down_revision = '0ea311529aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('client', sa.String(length=350), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'client')
    # ### end Alembic commands ###
